name: Branch Creation Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - 'feat/**'
      - 'main'

jobs:
  log-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Log branch name
        run: echo "Branch ${GITHUB_REF#refs/heads/} was created."
