name: Move Issue to In Progress

on:
  push:
    branches:
      - '**'

jobs:
  move-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Extract issue number from branch name
        run: echo "ISSUE_NUMBER=$(echo $GITHUB_REF | grep -oE '[0-9]+')" >> $GITHUB_ENV
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Move issue to In Progress
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/labels \
          -d '{"labels":["In Progress"]}'
