name: Issue Move Detector

on:
  projects_v2_item:
    types: [moved]

jobs:
  issue-move:
    runs-on: ubuntu-latest
    steps:
      - name: Echo issue move details
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER=$(echo "${{ github.event.project_item.content_url }}" | awk -F '/' '{print $NF}')
          OLD_COLUMN=$(echo "${{ github.event.project_item.old.column_name }}" | sed 's/"//g')
          NEW_COLUMN=$(echo "${{ github.event.project_item.new.column_name }}" | sed 's/"//g')
          
          echo "Issue #$ISSUE_NUMBER was moved from column '$OLD_COLUMN' to column '$NEW_COLUMN'."
