name: Log Moved Issue Details

on:
  project_column:
    types:
      - moved

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  checks: write
  actions: write
  contents: write
  issues: write

jobs:
  log-details:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract issue details
        id: extract-details
        run: |
          COLUMN_ID="${{ github.event.project_column.id }}"
          CONTENT_URL="${{ github.event.project_column.resource_url }}"
          
          # Extract the issue number from the content URL
          ISSUE_NUMBER=$(echo $CONTENT_URL | awk -F '/' '{print $NF}')
          
          # Echo the extracted details
          echo "Issue Number: $ISSUE_NUMBER"
          echo "Column ID: $COLUMN_ID"

      - name: Log moved issue details
        run: |
          echo "The issue ${{ steps.extract-details.outputs.issue-number }} was moved to column ${{ steps.extract-details.outputs.column-id }}"
