name: Log Moved Issue Details

on:
  project_card:
    types: [created, moved, converted, edited, deleted]
  project_column:
    types: [created, moved, updated, deleted]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  checks: write
  actions: write
  contents: write
  issues: write

jobs:
  log-details:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract issue details
        id: extract-details
        run: |
          ISSUE_NUMBER="${{ github.event.project_card.content_url }}"
          FROM_COLUMN_ID="${{ github.event.project_card.previous_column_id }}"
          TO_COLUMN_ID="${{ github.event.project_card.column_id }}"
          
          # Set the outputs for later steps
          echo "::set-output name=issue-number::$ISSUE_NUMBER"
          echo "::set-output name=from-column-id::$FROM_COLUMN_ID"
          echo "::set-output name=to-column-id::$TO_COLUMN_ID"

      - name: Log moved issue details
        run: |
          echo "The issue ${{ steps.extract-details.outputs.issue-number }} was moved from column ${{ steps.extract-details.outputs.from-column-id }} to column ${{ steps.extract-details.outputs.to-column-id }}"
