name: Issue Move Detector

on:
  project_card:
    types: [moved]

jobs:
  issue-move:
    runs-on: ubuntu-latest
    steps:
      - name: Echo issue move details
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CARD_CONTENT_URL=${{ github.event.project_card.content_url }}
          ISSUE_NUMBER=$(echo $CARD_CONTENT_URL | cut -d '/' -f  6)
          OLD_COLUMN=${{ github.event.changes.column_id.from }}
          NEW_COLUMN=${{ github.event.changes.column_id.to }}
          
          echo "Issue #$ISSUE_NUMBER was moved from column '$OLD_COLUMN' to column '$NEW_COLUMN'."
