name: Project Management Automation

on:
    issues:
        types: [opened, synchronize]
    pull_request:
        types: [opened, synchronize]
    repository_dispatch:
        types: [opened, synchronize]

jobs:
    close_done_issues:
        runs-on: ubuntu-latest
        if: github.event.project_card.column_id == 'Done'
        steps:
          - name: Close Issue
            run: |
                curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github+json" \
                https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
                -d '{ "state": "closed" }'
                
    reopen_issues:
        runs-on: ubuntu-latest
        if: github.event.project_card.column_id == 'In progress'
        steps:
          - name: Close Issue
            run: |
                curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github+json" \
                https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
                -d '{ "state": "Reopen" }'
                
